name: flutter_auth_ui
description: Unofficial firebaseui package for flutter. This library aims to provide support for Android, iOS and the web. Login with Email, Phone, Google account and etc.
version: 2.0.0
homepage: https://github.com/koji-1009/flutter_auth_ui

flutter:
  plugin:
    platforms:
      android:
        package: com.dr1009.app.flutter_auth_ui
        pluginClass: FlutterAuthUiPlugin
      ios:
        pluginClass: SwiftFlutterAuthUiPlugin
      web:
        default_package: flutter_auth_ui_web

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^1.0.0
  flutter_plugin_android_lifecycle: ^2.0.0
  flutter_auth_ui_web: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.22.0"
